CREATE TABLE access_tokens (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL,
  value TEXT NOT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);
