#!/usr/bin/env bash

if [ -n "$RUST_LOG" ]; then
  rust_log="-e RUST_LOG=$RUST_LOG"
else
  rust_log=""
fi

case "$1" in
  run|test)
    deps_opt=
    ;;
  *)
    deps_opt="--no-deps"
    ;;
esac

docker-compose run --rm $deps_opt -e RUST_BACKTRACE=1 $rust_log rust cargo "$@"
